# Generated by Django 3.1.6 on 2021-06-20 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ofDate', models.DateField()),
                ('noti', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('registerUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='call.vaccineregisteraton')),
            ],
        ),
    ]
