# Generated by Django 3.1.6 on 2021-06-20 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0003_auto_20210620_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='noti',
            field=models.CharField(max_length=15),
        ),
    ]
