# Generated by Django 3.1.6 on 2021-06-20 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0005_auto_20210620_1706'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vaccineregisteraton',
            old_name='for18',
            new_name='under18',
        ),
        migrations.RemoveField(
            model_name='vaccineregisteraton',
            name='for45',
        ),
    ]
