# Generated by Django 3.2.4 on 2021-06-22 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0006_auto_20210620_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccineregisteraton',
            name='token',
            field=models.TextField(default='aaa'),
            preserve_default=False,
        ),
    ]
