# Generated by Django 3.2.4 on 2021-06-24 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0008_vaccineregisteraton_dosetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccineregisteraton',
            name='paidType',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vaccineregisteraton',
            name='pincode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vaccineregisteraton',
            name='district_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
