# Generated by Django 3.2.4 on 2021-06-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0009_auto_20210624_0547'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='centerid',
            field=models.CharField(default='ss', max_length=15),
            preserve_default=False,
        ),
    ]
