# Generated by Django 3.2.4 on 2021-06-30 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0011_remove_notification_noti'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccineregisteraton',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='vaccineregisteraton',
            name='token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
